// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using URSBackend.Models;

namespace URSBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210603195710_Schedules")]
    partial class Schedules
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("URSBackend.Models.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClassCourseCourseCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassRoomCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Time2")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClassCourseCourseCode");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("URSBackend.Models.Course", b =>
                {
                    b.Property<string>("CourseCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreditHours")
                        .HasColumnType("int");

                    b.HasKey("CourseCode");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("URSBackend.Models.JoiningRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TargetClassroomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("TargetClassroomId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("URSBackend.Models.StudentClassroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentsClassrooms");
                });

            modelBuilder.Entity("URSBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("URSBackend.Models.Student", b =>
                {
                    b.HasBaseType("URSBackend.Models.User");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreditHoursPassed")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSemester")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("URSBackend.Models.Classroom", b =>
                {
                    b.HasOne("URSBackend.Models.Course", "ClassCourse")
                        .WithMany()
                        .HasForeignKey("ClassCourseCourseCode");

                    b.Navigation("ClassCourse");
                });

            modelBuilder.Entity("URSBackend.Models.JoiningRequest", b =>
                {
                    b.HasOne("URSBackend.Models.Student", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("URSBackend.Models.Classroom", "TargetClassroom")
                        .WithMany()
                        .HasForeignKey("TargetClassroomId");

                    b.Navigation("Client");

                    b.Navigation("TargetClassroom");
                });

            modelBuilder.Entity("URSBackend.Models.StudentClassroom", b =>
                {
                    b.HasOne("URSBackend.Models.Classroom", "ClassroomProp")
                        .WithMany("StudentsClassrooms")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("URSBackend.Models.Student", "StudentProp")
                        .WithMany("StudentsClassrooms")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassroomProp");

                    b.Navigation("StudentProp");
                });

            modelBuilder.Entity("URSBackend.Models.Classroom", b =>
                {
                    b.Navigation("StudentsClassrooms");
                });

            modelBuilder.Entity("URSBackend.Models.Student", b =>
                {
                    b.Navigation("StudentsClassrooms");
                });
#pragma warning restore 612, 618
        }
    }
}
